# Generated by Django 5.0.7 on 2024-08-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('codigo_barra', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
    ]
