# Generated by Django 5.0.7 on 2024-08-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0003_inventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='id_produtos',
            new_name='produto',
        ),
        migrations.AddField(
            model_name='producto',
            name='abreviaciones',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
