# Generated by Django 5.0.7 on 2024-08-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0004_rename_id_produtos_inventario_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='alta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='baja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
