# Generated by Django 5.0.7 on 2024-08-02 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0005_inventario_alta_inventario_baja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='alta',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='baja',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Project.categoria'),
        ),
        migrations.CreateModel(
            name='Registro_de_altas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Project.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_de_bajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Project.producto')),
            ],
        ),
    ]
