# Generated by Django 5.0.7 on 2024-08-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0007_inventario_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
