# Generated by Django 5.0.7 on 2024-08-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0008_alter_producto_codigo_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
