# Generated by Django 5.0.7 on 2024-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0009_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_barra'),
        ),
    ]
