# Generated by Django 5.0.7 on 2024-08-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0010_alter_producto_codigo_alter_producto_codigo_barra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_de_altas',
            old_name='produto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='registro_de_bajas',
            old_name='produto',
            new_name='producto',
        ),
    ]
