# Generated by Django 5.0.7 on 2024-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0012_rename_produto_inventario_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
