# Generated by Django 5.0.7 on 2024-08-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0013_producto_codigo_barra_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iba',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
