# Generated by Django 5.0.7 on 2024-08-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0014_producto_iba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='iba',
            field=models.IntegerField(choices=[(0, '0%'), (4, '4%'), (5, '5%'), (10, '10%'), (21, '21%')]),
        ),
        migrations.AlterField(
            model_name='registro_de_altas',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
