# Generated by Django 5.0.7 on 2024-08-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0015_alter_producto_iba_alter_registro_de_altas_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_de_altas',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registro_de_bajas',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
