# Generated by Django 5.0.7 on 2024-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0017_inventario_unidad_medida_inventario_valor_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='importe_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
