# Generated by Django 5.0.7 on 2024-08-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0018_inventario_importe_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_de_altas',
            name='pu',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
