# Generated by Django 5.0.7 on 2024-08-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0019_registro_de_altas_pu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_de_altas',
            old_name='pu',
            new_name='importe_total',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='importe_total',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='registro_de_altas',
            name='valor_unitario',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
