# Generated by Django 5.0.7 on 2024-08-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0020_rename_pu_registro_de_altas_importe_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('Gr', 'Gr'), ('Kg', 'Kg'), ('Ml', 'Ml'), ('Lt', 'Lt'), ('Cl', 'CL')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
